spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:./appdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 9090